### ISSUE TITLE
where is the filtered.h5 file

### ISSUE THREAD

**Issue by xxz19900** [IzarLab/CUIMC-NYP_COVID_autopsy_lung#1]
Recently, I'm reproducing the analysis according to the code "01_Individual_seurat_analysis.R". However, the h5 file could not been found. Would you please provide the link to the associated files? Thank you!

**Comment by JanaBiermann** [comment]
Hi Xu Xizhan,
The h5 file that serves as an input for "01_Individual_seurat_analysis.R" is the output of CellBender. If you want to rerun this particular script you can find the raw data at DUOS (https://duos.broadinstitute.org; study ID DUOS-000130). Alternatively, you can use the count data (corresponds to the Seurat 'RNA assay'), which is deposited at GEO (GSE171524; https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE171524) and the Single Cell Portal (https://singlecell.broadinstitute.org/single_cell/study/SCP1219).
